container:
    image: node:latest
    additional_containers:
      - name: mysql
        image: mysql:latest
        port: 3306
        cpu: 1.0
        memory: 512Mi
        env:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
task:
    environment:
        TEST: ENCRYPTED[c6846581446ab06a0ca9c3163ca76b19f2e59d3c8f1946ea7ac5c3c34caf705dcea8604652d2127fae1c64d8517466ea]
        GITKEY: ENCRYPTED[3440cec16c0bc8d21e69f99315f33a68f0574e256f6ab1efcb02ce932117d05111233d7748d7aea956f7159a50d74b81]
    script: 
    - node --version
    - echo "hello"
    - pwd
    - ls -la
    - cd
    - ls -la
    - mkdir .ssh
    - chmod 700 .ssh
    - cd .ssh
    - ls -la
    - echo "${GITKEY}" > id_ed25519
    - chmod 600 id_ed25519
    - ls -la
    - echo "cloning started"
    - git clone git@github.com:aniruddhnishad/mergify.git
